{% set name = "cf-view" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cf-view-{{ version }}.tar.gz
  sha256: ac69dd497c6c2940bedab4122abef4175d674a74b36187ab93e3dd59478db4f5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - cf-plot >=3.1.6
    - cf-python >=3.8.0
    - pyqt
    - python

test:
  imports:
    - cf_view
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ajheaps.github.io/cf-view
  summary: GUI for viewing CF files
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ajheaps
